### ISSUE TITLE
How to change the image on ContentView by tap gesture?

### ISSUE THREAD

**Issue by XiaoLinSoft** [mac-gallagher/MGSwipeCards#14]
Hi, How are you?
I am working on this CardStackView now.
How to change the image on ContentView by tap gesture?
I can't set the UITapGestureRecognizer in ContentView class.
Looking forward to your reply.
Thank you.

**Comment by mac-gallagher** [comment]
Here is a solution that comes to mind:

```swift
let cardModels: [CardModel]

func cardStack(_ cardStack: MGCardStackView, didSelectCardAt index: Int) {
    let oldModel = cardModels[index]
    let newImage = UIImage(named: "your_new_image")
    cardModels[index] = CardModel(image: newImage)
    cardStack.reloadData()
 }
```
(Note: You will need to set your card stack's delegate to recieve the tap) 

Of course, this is not the most efficient solution since the card stack is being reloaded after every tap, but it works.

**Comment by XiaoLinSoft** [comment]
Thank you.
