### ISSUE TITLE
How can I arrange the cards like this?

### ISSUE THREAD

**Issue by c941010623** [mac-gallagher/MGSwipeCards#2]
![1538635591859](https://user-images.githubusercontent.com/4303823/46457286-5a85f700-c7e4-11e8-9a79-d7c4bf3a8249.jpg)

can i get the sample code ?

**Comment by mac-gallagher** [comment]
Right now there is not really a good way to do this. I will work on adding this feature now

**Comment by mac-gallagher** [comment]
As of version 2.1.0, you can now override the method `transformForCard(at index: Int)` in `MGCardStackView` to provide custom card stack layouts.
